# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='account balance'),
        ),
    ]
